version: '3.8'
services:
  dev-db:
    image: postgres:13-alpine3.17
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: parking
    networks:
      - parking

networks:
  parking:
